export const properties = [
  {
    id: 1,
    name: "Maitama Heritage Residence",
    location: "Maitama, Abuja",
    price: "₦185M",
    per: "",
    badge: "For Sale",
    badgeType: "sale" as const,
    badge_type: "sale" as const,
    type: "house" as const,
    city: "Abuja",
    beds: 5,
    baths: 4,
    sqm: 420,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80",
  },
  {
    id: 2,
    name: "Asokoro Grand Villa",
    location: "Asokoro, Abuja",
    price: "₦320M",
    per: "",
    badge: "Under Construction",
    badgeType: "construction" as const,
    badge_type: "construction" as const,
    type: "house" as const,
    city: "Abuja",
    beds: 6,
    baths: 6,
    sqm: 680,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=700&q=80",
  },
  {
    id: 3,
    name: "Ikoyi Luxury Terrace",
    location: "Ikoyi, Lagos",
    price: "₦220M",
    per: "",
    badge: "For Sale",
    badgeType: "sale" as const,
    badge_type: "sale" as const,
    type: "house" as const,
    city: "Lagos",
    beds: 4,
    baths: 4,
    sqm: 380,
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=700&q=80",
  },
  {
    id: 4,
    name: "Lekki Phase 1 Duplex",
    location: "Lekki Phase 1, Lagos",
    price: "₦95M",
    per: "",
    badge: "For Sale",
    badgeType: "sale" as const,
    badge_type: "sale" as const,
    type: "house" as const,
    city: "Lagos",
    beds: 4,
    baths: 3,
    sqm: 290,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=700&q=80",
  },
  {
    id: 5,
    name: "Kaduna GRA Residential Plot",
    location: "GRA, Kaduna",
    price: "₦18M",
    per: "",
    badge: "Land",
    badgeType: "land" as const,
    badge_type: "land" as const,
    type: "land" as const,
    city: "Kaduna",
    beds: 0,
    baths: 0,
    sqm: 900,
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=700&q=80",
  },
  {
    id: 6,
    name: "Wuse II Commercial Plot",
    location: "Wuse II, Abuja",
    price: "₦45M",
    per: "",
    badge: "Land",
    badgeType: "land" as const,
    badge_type: "land" as const,
    type: "land" as const,
    city: "Abuja",
    beds: 0,
    baths: 0,
    sqm: 600,
    image: "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=700&q=80",
  },
  {
    id: 7,
    name: "Kano New Estate Development",
    location: "Nassarawa GRA, Kano",
    price: "₦62M",
    per: "",
    badge: "Under Construction",
    badgeType: "construction" as const,
    badge_type: "construction" as const,
    type: "house" as const,
    city: "Kano",
    beds: 3,
    baths: 3,
    sqm: 240,
  image: "/images/kano-house.svg",
  },
  {
    id: 8,
    name: "Victoria Island Corner Plot",
    location: "Victoria Island, Lagos",
    price: "₦130M",
    per: "",
    badge: "Land",
    badgeType: "land" as const,
    badge_type: "land" as const,
    type: "land" as const,
    city: "Lagos",
    beds: 0,
    baths: 0,
    sqm: 1200,
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=700&q=80",
  },
  {
    id: 9,
    name: "Garki Diplomat Mansion",
    location: "Garki, Abuja",
    price: "₦250M",
    per: "",
    badge: "For Sale",
    badgeType: "sale" as const,
    badge_type: "sale" as const,
    type: "house" as const,
    city: "Abuja",
    beds: 6,
    baths: 5,
    sqm: 560,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=700&q=80",
  },
  {
    id: 10,
    name: "Kaduna South Family Home",
    location: "Kaduna South, Kaduna",
    price: "₦55M",
    per: "",
    badge: "For Sale",
    badgeType: "sale" as const,
    badge_type: "sale" as const,
    type: "house" as const,
    city: "Kaduna",
    beds: 4,
    baths: 3,
    sqm: 300,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=700&q=80",
  },
  {
    id: 11,
    name: "Kano Commercial Land",
    location: "Fagge, Kano",
    price: "₦28M",
    per: "",
    badge: "Land",
    badgeType: "land" as const,
    badge_type: "land" as const,
    type: "land" as const,
    city: "Kano",
    beds: 0,
    baths: 0,
    sqm: 750,
  image: "/images/kano-house.svg",
  },
];

export const agents = [
  {
    id: 1,
    name: "Emeka Okafor",
    role: "Senior Listing Agent",
    specialisation: "Residential Sales",
    city: "Abuja",
    listings: 48,
    closed: "120+",
    bio: "Emeka has over eight years of experience in Abuja's residential market. He specialises in premium listings across Maitama, Asokoro, and Garki — and is known for his meticulous attention to client needs from first viewing to final signature.",
    phone: "+234 [Phone]",
    email: "emeka@neighbourhoodhomes.ng",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80",
  },
  {
    id: 2,
    name: "Adaeze Nwosu",
    role: "Luxury Property Specialist",
    specialisation: "Luxury & High-Value",
    city: "Lagos",
    listings: 35,
    closed: "89+",
    bio: "Adaeze operates at the top end of the Lagos market — Ikoyi, Victoria Island, and Lekki Phase 1. Her clients trust her for her discretion, market intelligence, and ability to negotiate complex high-value deals with precision.",
    phone: "+234 [Phone]",
    email: "adaeze@neighbourhoodhomes.ng",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
  },
  {
    id: 3,
    name: "Bello Musa",
    role: "Investment Consultant",
    specialisation: "Land & Investment",
    city: "Kaduna",
    listings: 62,
    closed: "175+",
    bio: "Bello is our most active agent by volume and leads all land acquisition activity across Kaduna and Kano. He has unparalleled knowledge of northern Nigeria's land market, making him the go-to consultant for investors building long-term portfolios.",
    phone: "+234 [Phone]",
    email: "bello@neighbourhoodhomes.ng",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
  },
  {
    id: 4,
    name: "Funke Adeola",
    role: "Residential Sales Agent",
    specialisation: "Off-plan & New Builds",
    city: "Abuja",
    listings: 29,
    closed: "64+",
    bio: "Funke specialises in off-plan and under-construction properties across Abuja. She helps buyers understand the opportunity and risk of early-stage developments and has a strong track record of securing excellent entry prices for clients.",
    phone: "+234 [Phone]",
    email: "funke@neighbourhoodhomes.ng",
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&q=80",
  },
  {
    id: 5,
    name: "Chidi Obi",
    role: "Sales Agent",
    specialisation: "Residential Sales",
    city: "Lagos",
    listings: 22,
    closed: "41+",
    bio: "Chidi is a rising talent on our Lagos team with a background in property valuation. He serves first-time buyers and investors looking for well-priced residential properties across Lekki and Lagos Mainland.",
    phone: "+234 [Phone]",
    email: "chidi@neighbourhoodhomes.ng",
    image: "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=400&q=80",
  },
  {
    id: 6,
    name: "Hauwa Abdullahi",
    role: "Land Sales Specialist",
    specialisation: "Land & Investment",
    city: "Kano",
    listings: 18,
    closed: "33+",
    bio: "Hauwa brings deep community knowledge to her role in the Kano market. She helps families and diaspora investors identify and secure titled land with confidence, and is fluent in both the technical and cultural nuances of the local market.",
    phone: "+234 [Phone]",
    email: "hauwa@neighbourhoodhomes.ng",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80",
  },
];

export const testimonials = [
  {
    id: 1,
    text: "Working with Neighbourhood Homes was the best decision I made this year. They found me a stunning property in Maitama within two weeks. Honest, efficient and truly professional.",
    name: "Mr. Jerry Tunde",
    role: "Business Executive, Abuja",
    image: "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=200&q=80",
  },
  {
    id: 2,
    text: "I invested in two properties through NHE and the ROI has been exceptional. Their investment analysis team is second to none in Nigeria. I trust them completely with my portfolio.",
    name: "Mrs. Ngozi Abara",
    role: "Business Owner, Lagos",
    image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&q=80",
  },
  {
    id: 3,
    text: "Neighbourhood Homes helped me secure a prime commercial plot in Kaduna. The documentation process was seamless — Neighbourhood Solicitors handled everything perfectly.",
    name: "Alhaji Isah Bamanga",
    role: "Investor, Kaduna",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  },
];

export const cities = [
  {
    name: "Abuja",
    count: "Houses, Land & Off-plan",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=900&q=80",
    span: true,
  },
  {
    name: "Lagos",
    count: "Houses & Land",
    image: "https://images.unsplash.com/photo-1618022325802-7e5e732d97a1?w=600&q=80",
    span: false,
  },
  {
    name: "Kaduna",
    count: "Houses & Land",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
    span: false,
  },
  {
    name: "Kano",
    count: "Houses, Land & Off-plan",
  image: "https://images.unsplash.com/photo-1560184897-6b3a5d1b2d1f?w=600&q=80",
    span: false,
  },
];
